//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// Generated from: fileformat.proto
using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace MSS.Tools.Pbf.IO.FileFormat
{
    [ProtoContract(IgnoreListHandling =false)]
    public class ByteList : List<byte>
    {
    }

    [ProtoContract(IgnoreListHandling = false)]
    public class ByteList1 : IEnumerable<byte>
    {
        //[ProtoMember(1)]
        public readonly List<byte> data = new List<byte>();

        public IEnumerator<byte> GetEnumerator()
        {
            return data.GetEnumerator();
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public bool Add(byte item)
        {
            this.data.Add(item);
            return true;
        }
    }


    /// <summary>
    /// 
    /// </summary>
    [global::ProtoBuf.ProtoContract(Name = @"Blob")]
    public partial class Blob2 : global::ProtoBuf.IExtensible
    {
        public void ClearForReUsage()
        {
            //this._raw_size = 0;
            //this._raw = null;
            //this.lzma_data = null;
            //this._bzip2_data = null;
            this.zlib_data = null;
        }
        /// <summary>
        /// 
        /// </summary>
        public Blob2()
        {
        }


        //private byte[] _raw = null;
        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"raw", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public byte[] raw
        //{
        //    get { return _raw; }
        //    set { _raw = value; }
        //}

        //private int _raw_size = default(int);
        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"raw_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        //[global::System.ComponentModel.DefaultValue(default(int))]
        //public int raw_size
        //{
        //    get { return _raw_size; }
        //    set { _raw_size = value; }
        //}

        private byte[] _zlib_data = null;

        /// <summary>
        /// 
        /// </summary>
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] zlib_data
        {
            get { return _zlib_data; }
            set { _zlib_data = value; }
        }

        //private ByteList _Zl = null;

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ByteList ZLib { get; set; }

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ArraySegment<byte> ZLib { get; set; }


        //public ByteList ZLib
        //{
        //    get
        //    {
        //        return _Zl;
        //    }
        //    set
        //    {
        //        value = _Zl;
        //    }
        //}

        //[ProtoBeforeDeserialization]
        //internal void OnDeserializingMethod(StreamingContext context)
        //{
        //    //_isDeserializingDerived = true;
        //}

        //[ProtoAfterDeserialization]
        //internal void OnDeserializedMethod(StreamingContext context)
        //{

        //}

        //private byte[] _lzma_data = null;
        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"lzma_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public byte[] lzma_data
        //{
        //    get { return _lzma_data; }
        //    set { _lzma_data = value; }
        //}

        //private byte[] _bzip2_data = null;
        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"bzip2_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public byte[] bzip2_data
        //{
        //    get { return _bzip2_data; }
        //    set { _bzip2_data = value; }
        //}
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }



}
