//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// Generated from: fileformat.proto
using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace MSS.Tools.Pbf.IO.FileFormat
{
    [ProtoContract(IgnoreListHandling =false)]
    public class ByteList : List<byte>
    {
    }

    [ProtoContract(IgnoreListHandling = false)]
    public class ByteList1 : IEnumerable<byte>
    {
        //[ProtoMember(1)]
        public readonly List<byte> data = new List<byte>();

        public IEnumerator<byte> GetEnumerator()
        {
            return data.GetEnumerator();
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public bool Add(byte item)
        {
            this.data.Add(item);
            return true;
        }
    }


    /// <summary>
    /// 
    /// </summary>
    [global::ProtoBuf.ProtoContract(Name = @"Blob")]
    public partial class Blob2 : global::ProtoBuf.IExtensible
    {
        public void ClearForReUsage()
        {
            this.zlib_data = null;
        }
        /// <summary>
        /// 
        /// </summary>
        public Blob2()
        {
        }

        private byte[] _zlib_data = null;

        /// <summary>
        /// 
        /// </summary>
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] zlib_data
        {
            get { return _zlib_data; }
            set { _zlib_data = value; }
        }

        //private ByteList _Zl = null;

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ByteList ZLib { get; set; }

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ArraySegment<byte> ZLib { get; set; }


        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}
