//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// Generated from: fileformat.proto
using ProtoBuf;
using ProtoBuf.Serializers;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace MSS.Tools.Pbf.IO.FileFormat
{


    //[ProtoContract]
    //struct BufferSurrogate
    //{//https://stackoverflow.com/questions/78185352/how-would-i-write-a-custom-protobuf-net-serializer-for-this-particular-class
    //    public static implicit operator BufferSurrogate(Blob2 value)
    //        => new BufferSurrogate { };
    //    public static implicit operator Blob2(BufferSurrogate value)
    //        => new Blob2 {};

    //    //public object? Value { get; set; }

    //    //[ProtoMember(1)]
    //    //public int? ValueInt32
    //    //{
    //    //    get => Value is int x ? x : default;
    //    //    set => Value = value;
    //    //}

    //    //[ProtoMember(2)]
    //    //public string? ValueString
    //    //{
    //    //    get => Value as string;
    //    //    set => Value = value;
    //    //}

    //    //[ProtoMember(3)]
    //    //public Foo? ValueFoo
    //    //{
    //    //    get => Value as Foo;
    //    //    set => Value = value;
    //    //}
    //}
    //public class ByteSerializer : ISerializer<ByteBuffer>
    //{
    //    public SerializerFeatures Features => throw new NotImplementedException();

    //    public ByteBuffer Read(ref ProtoReader.State state, ByteBuffer value)
    //    {
    //        throw new NotImplementedException();
    //    }

    //    public void Write(ref ProtoWriter.State state, ByteBuffer value)
    //    {
    //        throw new NotImplementedException();
    //    }
    //}

    //[ProtoContract(Serializer = typeof(ByteSerializer))]
    //public class ByteBuffer
    //{ }

    [ProtoContract(IgnoreListHandling =true)]
    public class NotAByteList : List<byte>
    {
    }

    [ProtoContract(IgnoreListHandling = false)]
    public class ByteList : List<byte>
    {
    }

    [ProtoContract(IgnoreListHandling = false)]
    public class ByteList1 : IEnumerable<byte>
    {
        //[ProtoMember(1)]
        public readonly List<byte> data = new List<byte>();

        public IEnumerator<byte> GetEnumerator()
        {
            return data.GetEnumerator();
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public bool Add(byte item)
        {
            this.data.Add(item);
            return true;
        }
    }


    /// <summary>
    /// 
    /// </summary>
    [global::ProtoBuf.ProtoContract(Name = @"Blob")]
    public partial class Blob2 : global::ProtoBuf.IExtensible
    {
        public void ClearForReUsage()
        {
            //this.zlib_data = null;
        }
        /// <summary>
        /// 
        /// </summary>
        public Blob2()
        {
        }


        private ArraySegment<byte> _zlib_data = null;

        /// <summary>
        /// 
        /// </summary>
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ArraySegment<byte> zlib_data
        {
            get { return _zlib_data; }
            set { _zlib_data = value; }
        }

        //private byte[] _zlib_data = null;

        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public byte[] zlib_data
        //{
        //    get { return _zlib_data; }
        //    set { _zlib_data = value; }
        //}

        //private NotAByteList _Zl = null;

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public NotAByteList ZLib { get; set; }


        //private ByteList _Zl = null;

        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ByteList ZLib { get; set; }




        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public ArraySegment<byte> ZLib { get; set; }

        //private List<sbyte> _zlib_data;

        ///// <summary>
        ///// 
        ///// </summary>
        //[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"zlib_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(null)]
        //public List<sbyte> zlib_data
        //{
        //    get { return _zlib_data; }
        //    set { _zlib_data = value; }
        //}


        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}
